import ApiService from "./apiService";

// ========== TASK MANAGEMENT ==========

/**
 * Create a new task
 * @param {Object} taskBody - Task data matching API requirements:
 *   - task (string, required)
 *   - description (string, optional)
 *   - phaseId (uuid, required)
 *   - status (string, required): "pending"|"ongoing"|"review"|"completed"|"failed"
 *   - priority (string, optional): "low"|"medium"|"high"|"urgent"
 *   - dueDate (string, ISO date, optional)
 *   - assignee (string|null, optional)
 *   - comments (number, optional, default: 0)
 *   - views (number, optional, default: 0)
 *   - order (number, optional)
 *   - updatedBy (string, optional)
 * Note: taskId is auto-generated by the backend, so it should not be included in the request body.
 */
export async function createTask(taskBody) {
    // Ensure taskId is never sent to the backend
    const cleanTaskBody = { ...taskBody };
    delete cleanTaskBody.taskId;
    delete cleanTaskBody._id;
    delete cleanTaskBody.id;
    
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks`;
    apiObject.body = cleanTaskBody;
    return await ApiService.callApi(apiObject);
}

/**
 * Update an existing task
 * @param {string} taskId - The UUID of the task to update
 * @param {Object} taskBody - Task data to update (taskId should not be included)
 */
export async function updateTask(taskId, taskBody) {
    // Ensure taskId is never sent in the body (it's in the URL)
    const cleanTaskBody = { ...taskBody };
    delete cleanTaskBody.taskId;
    delete cleanTaskBody._id;
    delete cleanTaskBody.id;
    
    const apiObject = {};
    apiObject.method = "PUT";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}`;
    apiObject.body = cleanTaskBody;
    return await ApiService.callApi(apiObject);
}


/**
 * Delete a task
 */
export async function deleteTask(taskId) {
    const apiObject = {};
    apiObject.method = "DELETE";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Update task position (for drag and drop)
 */
export async function updateTaskPosition(taskId, positionData) {
    const apiObject = {};
    apiObject.method = "PATCH";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/position`;
    apiObject.body = positionData;
    return await ApiService.callApi(apiObject);
}

/**
 * Get tasks for a specific phase with filters
 * Note: Backend doesn't have a "get all tasks" endpoint.
 * Use getPhaseTasks() to get tasks for each phase, or use getAllPhase(includeTasks=true) to get phases with tasks.
 */
export async function getAllTasks(filters = {}) {
    // This function is kept for backward compatibility but should not be used
    // Instead, use getPhaseTasks() for each phase or getAllPhase(includeTasks=true)
    console.warn('getAllTasks() is deprecated. Use getPhaseTasks(phaseId) or getAllPhase(includeTasks=true) instead.');
    return { data: [] };
}

// ========== PHASE MANAGEMENT ==========

/**
 * Get all phases
 */
export async function getAllPhase(includeTasks = false) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    const queryParam = includeTasks ? '?includeTasks=true' : '';
    apiObject.endpoint = `tasks/phases${queryParam}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Create a new phase
 */
export async function createPhase(phaseBody) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/phases`;
    apiObject.body = phaseBody;
    return await ApiService.callApi(apiObject);
}

/**
 * Update a phase
 */
export async function updatePhaseById(phaseId, phaseBody) {
    const apiObject = {};
    apiObject.method = "PUT";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/phases/${phaseId}`;
    apiObject.body = phaseBody;
    return await ApiService.callApi(apiObject);
}

/**
 * Delete a phase
 */
export async function deletePhase(phaseId, reassignPhaseId = null) {
    const apiObject = {};
    apiObject.method = "DELETE";
    apiObject.authentication = true;
    const queryParam = reassignPhaseId ? `?reassignPhaseId=${reassignPhaseId}` : '';
    apiObject.endpoint = `tasks/phases/${phaseId}${queryParam}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Get tasks for a specific phase with filters
 */
export async function getPhaseTasks(phaseId, filters = {}) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    
    // Build query string
    const queryParams = new URLSearchParams();
    if (filters.status) {
        const statusArray = Array.isArray(filters.status) ? filters.status : [filters.status];
        statusArray.forEach(status => queryParams.append('status', status));
    }
    if (filters.dateFrom) queryParams.append('dateFrom', filters.dateFrom);
    if (filters.dateTo) queryParams.append('dateTo', filters.dateTo);
    if (filters.search) queryParams.append('search', filters.search);
    
    const queryString = queryParams.toString();
    apiObject.endpoint = `tasks/phases/${phaseId}/tasks${queryString ? `?${queryString}` : ''}`;
    return await ApiService.callApi(apiObject);
}

// ========== REFERENCE DATA ==========

/**
 * Get reference data for task statuses
 */
export async function getTaskStatuses() {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/reference/statuses`;
    return await ApiService.callApi(apiObject);
}
