import ApiService from "./apiService";

// ========== TASK MANAGEMENT ==========

/**
 * Create a new task
 * @param {Object} taskBody - Task data matching API requirements:
 *   - task (string, required)
 *   - description (string, optional)
 *   - phaseId (uuid, required)
 *   - status (string, required): "pending"|"ongoing"|"review"|"completed"|"failed"
 *   - priority (string, optional): "low"|"medium"|"high"|"urgent"
 *   - dueDate (string, ISO date, optional)
 *   - assignedUserId (uuid, optional) - NEW: User UUID to assign task to
 *   - costingId (uuid, optional) - NEW: Costing UUID to associate with task
 *   - assignee (string|null, optional) - Legacy field for backward compatibility
 *   - comments (number, optional, default: 0)
 *   - views (number, optional, default: 0)
 *   - order (number, optional)
 *   - updatedBy (string, optional)
 * Note: taskId is auto-generated by the backend, so it should not be included in the request body.
 */
export async function createTask(taskBody) {
    // Ensure taskId is never sent to the backend
    const cleanTaskBody = { ...taskBody };
    delete cleanTaskBody.taskId;
    delete cleanTaskBody._id;
    delete cleanTaskBody.id;
    
    // Remove assignees array if present (API only supports single assignedUserId)
    if (cleanTaskBody.assignees && Array.isArray(cleanTaskBody.assignees)) {
        // If assignees array exists, use first one as assignedUserId
        if (cleanTaskBody.assignees.length > 0 && !cleanTaskBody.assignedUserId) {
            cleanTaskBody.assignedUserId = cleanTaskBody.assignees[0];
        }
        delete cleanTaskBody.assignees;
    }
    
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks`;
    apiObject.body = cleanTaskBody;
    return await ApiService.callApi(apiObject);
}

/**
 * Update an existing task
 * @param {string} taskId - The UUID of the task to update
 * @param {Object} taskBody - Task data to update (taskId should not be included)
 *   - assignedUserId (uuid|null, optional) - Update assigned user (null to unassign)
 *   - costingId (uuid|null, optional) - Update costing (null to unassign)
 */
export async function updateTask(taskId, taskBody) {
    // Ensure taskId is never sent in the body (it's in the URL)
    const cleanTaskBody = { ...taskBody };
    delete cleanTaskBody.taskId;
    delete cleanTaskBody._id;
    delete cleanTaskBody.id;
    
    // Remove assignees array if present (API only supports single assignedUserId)
    if (cleanTaskBody.assignees && Array.isArray(cleanTaskBody.assignees)) {
        // If assignees array exists, use first one as assignedUserId
        if (cleanTaskBody.assignees.length > 0 && !cleanTaskBody.assignedUserId) {
            cleanTaskBody.assignedUserId = cleanTaskBody.assignees[0];
        } else if (cleanTaskBody.assignees.length === 0) {
            // Empty array means unassign
            cleanTaskBody.assignedUserId = null;
        }
        delete cleanTaskBody.assignees;
    }
    
    const apiObject = {};
    apiObject.method = "PUT";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}`;
    apiObject.body = cleanTaskBody;
    return await ApiService.callApi(apiObject);
}


/**
 * Delete a task
 */
export async function deleteTask(taskId) {
    const apiObject = {};
    apiObject.method = "DELETE";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Get task by ID
 * @param {string} taskId - Task ID (UUID or taskId string)
 */
export async function getTaskById(taskId) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Get task details with recipe information
 * @param {string} taskId - Task ID (UUID or taskId string)
 */
export async function getTaskDetails(taskId) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/details`;
    return await ApiService.callApi(apiObject);
}

/**
 * Update task position (for drag and drop)
 */
export async function updateTaskPosition(taskId, positionData) {
    const apiObject = {};
    apiObject.method = "PATCH";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/position`;
    apiObject.body = positionData;
    return await ApiService.callApi(apiObject);
}

/**
 * Get tasks for a specific phase with filters
 * Note: Backend doesn't have a "get all tasks" endpoint.
 * Use getPhaseTasks() to get tasks for each phase, or use getAllPhase(includeTasks=true) to get phases with tasks.
 */
export async function getAllTasks(filters = {}) {
    // This function is kept for backward compatibility but should not be used
    // Instead, use getPhaseTasks() for each phase or getAllPhase(includeTasks=true)
    console.warn('getAllTasks() is deprecated. Use getPhaseTasks(phaseId) or getAllPhase(includeTasks=true) instead.');
    return { data: [] };
}

// ========== PHASE MANAGEMENT ==========

/**
 * Get all phases
 */
export async function getAllPhase(includeTasks = false) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    const queryParam = includeTasks ? '?includeTasks=true' : '';
    apiObject.endpoint = `tasks/phases${queryParam}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Create a new phase
 */
export async function createPhase(phaseBody) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/phases`;
    apiObject.body = phaseBody;
    return await ApiService.callApi(apiObject);
}

/**
 * Update a phase
 */
export async function updatePhaseById(phaseId, phaseBody) {
    const apiObject = {};
    apiObject.method = "PUT";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/phases/${phaseId}`;
    apiObject.body = phaseBody;
    return await ApiService.callApi(apiObject);
}

/**
 * Delete a phase
 */
export async function deletePhase(phaseId, reassignPhaseId = null) {
    const apiObject = {};
    apiObject.method = "DELETE";
    apiObject.authentication = true;
    const queryParam = reassignPhaseId ? `?reassignPhaseId=${reassignPhaseId}` : '';
    apiObject.endpoint = `tasks/phases/${phaseId}${queryParam}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Get tasks for a specific phase with filters
 */
export async function getPhaseTasks(phaseId, filters = {}) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    
    // Build query string
    const queryParams = new URLSearchParams();
    if (filters.status) {
        const statusArray = Array.isArray(filters.status) ? filters.status : [filters.status];
        statusArray.forEach(status => queryParams.append('status', status));
    }
    if (filters.dateFrom) queryParams.append('dateFrom', filters.dateFrom);
    if (filters.dateTo) queryParams.append('dateTo', filters.dateTo);
    if (filters.search) queryParams.append('search', filters.search);
    
    const queryString = queryParams.toString();
    apiObject.endpoint = `tasks/phases/${phaseId}/tasks${queryString ? `?${queryString}` : ''}`;
    return await ApiService.callApi(apiObject);
}

// ========== REFERENCE DATA ==========

/**
 * Get reference data for task statuses
 */
export async function getTaskStatuses() {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/status-reference`;
    return await ApiService.callApi(apiObject);
}

// ========== TASK COMMENT MANAGEMENT ==========

/**
 * Add a comment to a task
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {Object} commentData - Comment data:
 *   - comment (string, required): The comment text
 *   - ownerId (string, optional): User UUID (if provided, ownerName/ownerEmail will be auto-filled)
 *   - ownerName (string, optional): Owner name (if ownerId not provided)
 *   - ownerEmail (string, optional): Owner email (if ownerId not provided)
 */
export async function addTaskComment(taskId, commentData) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/comments`;
    apiObject.body = commentData;
    return await ApiService.callApi(apiObject);
}

/**
 * Get all comments for a task
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @returns {Promise} Array of comments ordered by most recent first
 */
export async function getTaskComments(taskId) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/comments`;
    return await ApiService.callApi(apiObject);
}

/**
 * Delete a comment
 * @param {string} commentId - Comment ID (UUID)
 */
export async function deleteTaskComment(commentId) {
    const apiObject = {};
    apiObject.method = "DELETE";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/comments/${commentId}`;
    return await ApiService.callApi(apiObject);
}

// ========== TASK PHASE MOVEMENT ==========

/**
 * Move a task to another phase
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {Object} movementData - Movement data:
 *   - toPhaseId (string, required): UUID of target phase
 *   - toStatus (string, optional): Status in new phase (defaults to first status of target phase)
 *   - order (number, optional): Target order position (defaults to next available)
 *   - reason (string, optional): Reason/notes for movement
 *   - movedBy (string, optional): User UUID or name who initiated the move
 */
export async function moveTaskToPhase(taskId, movementData) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/move`;
    apiObject.body = movementData;
    return await ApiService.callApi(apiObject);
}

/**
 * Get task movement history
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {Object} options - Query options:
 *   - limit (number, optional): Maximum number of records (default: 50, max: 100)
 *   - offset (number, optional): Number of records to skip (default: 0)
 */
export async function getTaskMovementHistory(taskId, options = {}) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    
    // Build query string
    const queryParams = new URLSearchParams();
    if (options.limit) queryParams.append('limit', options.limit.toString());
    if (options.offset) queryParams.append('offset', options.offset.toString());
    
    const queryString = queryParams.toString();
    apiObject.endpoint = `tasks/${taskId}/movement-history${queryString ? `?${queryString}` : ''}`;
    return await ApiService.callApi(apiObject);
}

// ========== RECIPE EXECUTION MANAGEMENT ==========

/**
 * Start recipe execution for a task
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {string} recipeId - Optional recipe ID (will auto-find from costed product if not provided)
 */
export async function startRecipeExecution(taskId, recipeId = null) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/start`;
    apiObject.body = recipeId ? { recipeId } : {};
    return await ApiService.callApi(apiObject);
}

/**
 * Pause recipe execution
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {Object} pauseData - Pause data:
 *   - reason (string, optional): Reason for pausing
 *   - remainingTime (number, optional): Remaining time in minutes (from frontend timer)
 */
export async function pauseRecipeExecution(taskId, pauseData = {}) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/pause`;
    apiObject.body = pauseData;
    return await ApiService.callApi(apiObject);
}

/**
 * Resume paused recipe execution
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {Object} resumeData - Resume data:
 *   - notes (string, optional): Notes about resuming
 *   - remainingTime (number, optional): Remaining time in minutes (from frontend timer)
 */
export async function resumeRecipeExecution(taskId, resumeData = {}) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/resume`;
    apiObject.body = resumeData;
    return await ApiService.callApi(apiObject);
}

/**
 * Start a specific step in recipe execution
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {number} stepOrder - Step order number to start (1, 2, 3, ...)
 */
export async function startStep(taskId, stepOrder) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/steps/${stepOrder}/start`;
    apiObject.body = {};
    return await ApiService.callApi(apiObject);
}

/**
 * Update step progress
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {number} stepOrder - Step order number (1, 2, 3, ...)
 * @param {Object} progressData - Progress data:
 *   - progress (number, required): 0-100
 *   - actualTemperature (number, optional)
 *   - notes (string, optional)
 */
export async function updateStepProgress(taskId, stepOrder, progressData) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/steps/${stepOrder}/progress`;
    apiObject.body = progressData;
    return await ApiService.callApi(apiObject);
}

/**
 * Complete a step
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {number} stepOrder - Step order number (1, 2, 3, ...)
 * @param {Object} completionData - Completion data:
 *   - actualDuration (number, optional): Actual duration in minutes (alternative to remainingTime)
 *   - remainingTime (number, optional): Remaining time in minutes (alternative to actualDuration)
 *   - actualTemperature (number, optional)
 *   - notes (string, optional)
 */
export async function completeStep(taskId, stepOrder, completionData = {}) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/steps/${stepOrder}/complete`;
    apiObject.body = completionData;
    return await ApiService.callApi(apiObject);
}

/**
 * Cancel recipe execution
 * @param {string} taskId - Task ID (UUID or taskId string)
 */
export async function cancelRecipeExecution(taskId) {
    const apiObject = {};
    apiObject.method = "POST";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/cancel`;
    apiObject.body = {};
    return await ApiService.callApi(apiObject);
}

/**
 * Get recipe execution status
 * @param {string} taskId - Task ID (UUID or taskId string)
 */
export async function getRecipeExecutionStatus(taskId) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/status`;
    return await ApiService.callApi(apiObject);
}

/**
 * Get task template for a specific phase
 * @param {string} phaseId - Phase ID (UUID)
 * @returns {Promise} Template object with required/optional fields and field descriptions
 */
export async function getTaskTemplate(phaseId) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/template/${phaseId}`;
    return await ApiService.callApi(apiObject);
}

/**
 * Get task status by order number (Public endpoint - no authentication required)
 * @param {string} orderNumber - Order number
 * @returns {Promise} Task status data including order details, task info, phase, and customer info
 */
export async function getTaskStatusByOrderNumber(orderNumber) {
    const apiObject = {};
    apiObject.method = "GET";
    apiObject.authentication = false; // Public endpoint, no authentication
    apiObject.endpoint = `tasks/public/status/${orderNumber}`;
    return await ApiService.callApi(apiObject);
}

// ========== PREPARATION QUESTION MANAGEMENT ==========

/**
 * Update preparation question checkbox status
 * @param {string} taskId - Task ID (UUID or taskId string)
 * @param {string} preparationStepId - Preparation step ID (UUID)
 * @param {string} questionId - Question ID (UUID)
 * @param {Object} statusData - Status data:
 *   - checked (boolean, required): Whether the checkbox is checked or unchecked
 */
export async function updatePreparationQuestionStatus(taskId, preparationStepId, questionId, statusData) {
    const apiObject = {};
    apiObject.method = "PATCH";
    apiObject.authentication = true;
    apiObject.endpoint = `tasks/${taskId}/recipe/preparation/${preparationStepId}/questions/${questionId}/check`;
    apiObject.body = statusData;
    return await ApiService.callApi(apiObject);
}
