import React, { useEffect } from 'react';
import { Modal, Form, Input, Select, DatePicker, message ,Row, Col} from 'antd';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import dayjs from 'dayjs';
import { TASK_STATUS, TASK_PRIORITY, TASK_STATUS_LABELS, TASK_PRIORITY_LABELS } from './types';
import { kanbanUsers, findKanbanUser } from './data/users';

const { TextArea } = Input;
const { Option } = Select;

// Helper function to get current user ID from sessionStorage
const getCurrentUserId = () => {
  try {
    const authUser = sessionStorage.getItem('authUser');
    if (authUser) {
      const user = JSON.parse(authUser);
      return user.user?._id || user.user?.id || user._id || user.id || null;
    }
  } catch (error) {
    console.error('Error getting current user:', error);
  }
  return null;
};

const AddTaskModal = ({ visible, onCancel, onOk, phaseId, initialValues }) => {
  const [form] = Form.useForm();

  const validationSchema = Yup.object({
    task: Yup.string().required('Task title is required'),
    status: Yup.string().required('Status is required'),
    phaseId: Yup.string().required('Phase is required'),
  });

  const formik = useFormik({
    initialValues: initialValues || {
      task: '',
      description: '',
      dueDate: null,
      status: TASK_STATUS.PENDING,
      priority: TASK_PRIORITY.MEDIUM,
      phaseId: phaseId || '',
      order: 0,
      comments: 0,
      views: 0,
      assignees: kanbanUsers[0]?.id ? [kanbanUsers[0].id] : [],
    },
    validationSchema,
    onSubmit: (values) => {
      // Get current user for updatedBy field
      const updatedBy = getCurrentUserId();
      
      // Prepare task data according to API requirements
      // Note: taskId is auto-generated by backend, so we explicitly exclude it
      // Only include fields that are allowed in the API request
      const taskData = {
        task: values.task,
        phaseId: values.phaseId,
        status: values.status,
      };

      // Add optional fields only if they have values
      if (values.description) {
        taskData.description = values.description;
      }
      if (values.priority) {
        taskData.priority = values.priority;
      }
      if (values.dueDate) {
        taskData.dueDate = dayjs(values.dueDate).toISOString();
      }
      if (values.assignees && values.assignees.length > 0) {
        taskData.assignees = values.assignees; // Send as array for multiple assignees
      }
      if (values.comments !== undefined && values.comments !== null) {
        taskData.comments = values.comments;
      }
      if (values.views !== undefined && values.views !== null) {
        taskData.views = values.views;
      }
      if (values.order !== undefined && values.order !== null) {
        taskData.order = values.order;
      }
      if (updatedBy) {
        taskData.updatedBy = updatedBy;
      }

      // Ensure taskId is never included (explicit check)
      if ('taskId' in taskData) {
        delete taskData.taskId;
      }

      onOk(taskData);
      formik.resetForm();
      form.resetFields();
    },
  });

  useEffect(() => {
    const defaultAssignee = kanbanUsers[0]?.id || null;
    if (initialValues) {
      // Parse ISO date string or existing format
      let parsedDate = null;
      if (initialValues.dueDate) {
        if (typeof initialValues.dueDate === 'string') {
          // Try ISO format first
          parsedDate = dayjs(initialValues.dueDate).isValid() 
            ? dayjs(initialValues.dueDate) 
            : dayjs(initialValues.dueDate, 'DD MMM, YYYY');
        } else {
          parsedDate = dayjs(initialValues.dueDate);
        }
      }
      
      // Handle assignees - could be array, string (ID), or object
      let assigneesValue = [];
      if (initialValues.assignees && Array.isArray(initialValues.assignees)) {
        // If it's already an array, use it
        assigneesValue = initialValues.assignees.map(a => typeof a === 'string' ? a : (a?.id || a));
      } else if (initialValues.assignee) {
        // Legacy single assignee - convert to array
        assigneesValue = typeof initialValues.assignee === 'string' 
          ? [initialValues.assignee] 
          : [initialValues.assignee?.id || defaultAssignee].filter(Boolean);
      } else {
        assigneesValue = defaultAssignee ? [defaultAssignee] : [];
      }

      // Remove taskId from initialValues when editing (it's read-only, auto-generated by backend)
      const { taskId: _, ...initialValuesWithoutId } = initialValues;

      formik.setValues({
        ...initialValuesWithoutId,
        dueDate: parsedDate && parsedDate.isValid() ? parsedDate : null,
        assignees: assigneesValue,
      });
      form.setFieldsValue({
        ...initialValuesWithoutId,
        dueDate: parsedDate && parsedDate.isValid() ? parsedDate : null,
        assignees: assigneesValue,
      });
    } else {
      if (phaseId) {
        formik.setFieldValue('phaseId', phaseId);
        form.setFieldsValue({ phaseId });
      }
      const currentAssignees = formik.values.assignees || (defaultAssignee ? [defaultAssignee] : []);
      formik.setFieldValue('assignees', currentAssignees);
      form.setFieldsValue({ assignees: currentAssignees });
    }
  }, [initialValues, phaseId]);

  const handleOk = async () => {
    try {
      await form.validateFields();
      formik.handleSubmit();
    } catch (error) {
      message.error('Please fill in all required fields');
    }
  };

  const handleCancel = () => {
    formik.resetForm();
    form.resetFields();
    onCancel();
  };

  return (
    <Modal
      title={initialValues ? 'Edit Task' : 'Add New Task'}
      open={visible}
      onOk={handleOk}
      onCancel={handleCancel}
      width={600}
      okText="Save"
      cancelText="Cancel"
    >
      <Form
        form={form}
        layout="vertical"
        onValuesChange={(changedValues, allValues) => {
          Object.keys(changedValues).forEach((key) => {
            formik.setFieldValue(key, allValues[key]);
          });
        }}
      >
      <Form.Item
        label="Task Title"
        name="task"
        rules={[{ required: true, message: 'Please enter task title' }]}
      >
        <Input
          value={formik.values.task}
          onChange={formik.handleChange}
          placeholder="Enter task title"
        />
      </Form.Item>

      <Form.Item label="Description" name="description">
        <TextArea
          value={formik.values.description}
          onChange={formik.handleChange}
          placeholder="Enter task description (optional)"
          rows={3}
        />
      </Form.Item>

      <Row gutter={16}>
        <Col span={12}>
          <Form.Item
            label="Assign To"
            name="assignees"
            rules={[{ required: true, message: 'Please select at least one user' }]}
          >
            <Select
              mode="multiple"
              value={formik.values.assignees}
              onChange={(value) => formik.setFieldValue('assignees', value)}
              placeholder="Select one or more users"
              allowClear
              maxTagCount="responsive"
              showSearch
              filterOption={(input, option) =>
                (option?.children?.toLowerCase() ?? '').includes(input.toLowerCase())
              }
            >
              {kanbanUsers.map((user) => (
                <Option key={user.id} value={user.id}>
                  {user.name} {user.role ? `(${user.role})` : ''}
                </Option>
              ))}
            </Select>
          </Form.Item>
        </Col>
        <Col span={12}>
          <Form.Item
            label="Status"
            name="status"
            rules={[{ required: true, message: 'Please select status' }]}
          >
            <Select
              value={formik.values.status}
              onChange={(value) => formik.setFieldValue('status', value)}
            >
              {Object.keys(TASK_STATUS_LABELS).map((status) => (
                <Option key={status} value={status}>
                  {TASK_STATUS_LABELS[status]}
                </Option>
              ))}
            </Select>
          </Form.Item>
        </Col>
      </Row>

      <Row gutter={16}>
        <Col span={12}>
          <Form.Item label="Priority" name="priority">
            <Select
              value={formik.values.priority}
              onChange={(value) => formik.setFieldValue('priority', value)}
              placeholder="Select priority (optional)"
            >
              {Object.keys(TASK_PRIORITY_LABELS).map((priority) => (
                <Option key={priority} value={priority}>
                  {TASK_PRIORITY_LABELS[priority]}
                </Option>
              ))}
            </Select>
          </Form.Item>
        </Col>
        <Col span={12}>
          <Form.Item label="Due Date" name="dueDate">
            <DatePicker
              style={{ width: '100%' }}
              value={formik.values.dueDate}
              onChange={(date) => formik.setFieldValue('dueDate', date)}
              format="YYYY-MM-DD"
              showTime={false}
            />
          </Form.Item>
        </Col>
      </Row>
      </Form>
    
    </Modal>
  );
};

export default AddTaskModal;

